CREATE TABLE "hero_slides" (
	"id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"image_url" text NOT NULL,
	"link_url" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- 既存のヒーロー画像を初期投入（カルーセル5枚 + 背景44枚）
INSERT INTO "hero_slides" ("id", "type", "image_url", "link_url", "sort_order") VALUES
	(gen_random_uuid()::text, 'carousel', '/hero/hero1.jpg', 'https://www.ik-alumni-cgt.com/information/msF6BJczMaceyFyaYXiOh', 0),
	(gen_random_uuid()::text, 'carousel', '/hero/hero2.jpg', 'https://www.ik-alumni-cgt.com/supporters', 1),
	(gen_random_uuid()::text, 'carousel', '/hero/hero3.jpg', 'https://www.ik-alumni-cgt.com/information/tO6hO-rok6TmGAydrXtXV', 2),
	(gen_random_uuid()::text, 'carousel', '/hero/hero4.jpg', 'https://linktr.ee/ik_alumni_2022', 3),
	(gen_random_uuid()::text, 'carousel', '/hero/hero5.jpg', 'https://www.ik-alumni-cgt.com/information/Q0qmGTSBsw4KsQLK0OTGW', 4);
--> statement-breakpoint
INSERT INTO "hero_slides" ("id", "type", "image_url", "link_url", "sort_order") VALUES
	(gen_random_uuid()::text, 'background', '/hero-bg/１.jpg', NULL, 0),
	(gen_random_uuid()::text, 'background', '/hero-bg/２.jpg', NULL, 1),
	(gen_random_uuid()::text, 'background', '/hero-bg/３.jpg', NULL, 2),
	(gen_random_uuid()::text, 'background', '/hero-bg/４.jpg', NULL, 3),
	(gen_random_uuid()::text, 'background', '/hero-bg/５.JPG', NULL, 4),
	(gen_random_uuid()::text, 'background', '/hero-bg/６.JPG', NULL, 5),
	(gen_random_uuid()::text, 'background', '/hero-bg/７.jpg', NULL, 6),
	(gen_random_uuid()::text, 'background', '/hero-bg/８.JPEG', NULL, 7),
	(gen_random_uuid()::text, 'background', '/hero-bg/９.JPEG', NULL, 8),
	(gen_random_uuid()::text, 'background', '/hero-bg/１０.JPEG', NULL, 9),
	(gen_random_uuid()::text, 'background', '/hero-bg/１１.jpg', NULL, 10),
	(gen_random_uuid()::text, 'background', '/hero-bg/１２.JPG', NULL, 11),
	(gen_random_uuid()::text, 'background', '/hero-bg/１３.jpg', NULL, 12),
	(gen_random_uuid()::text, 'background', '/hero-bg/１４.JPEG', NULL, 13),
	(gen_random_uuid()::text, 'background', '/hero-bg/１５.jpg', NULL, 14),
	(gen_random_uuid()::text, 'background', '/hero-bg/１６.jpg', NULL, 15),
	(gen_random_uuid()::text, 'background', '/hero-bg/１７.JPG', NULL, 16),
	(gen_random_uuid()::text, 'background', '/hero-bg/１８.JPEG', NULL, 17),
	(gen_random_uuid()::text, 'background', '/hero-bg/１９.jpg', NULL, 18),
	(gen_random_uuid()::text, 'background', '/hero-bg/２０.JPG', NULL, 19),
	(gen_random_uuid()::text, 'background', '/hero-bg/２１.JPG', NULL, 20),
	(gen_random_uuid()::text, 'background', '/hero-bg/２２.JPG', NULL, 21),
	(gen_random_uuid()::text, 'background', '/hero-bg/２３.JPG', NULL, 22),
	(gen_random_uuid()::text, 'background', '/hero-bg/２４.JPG', NULL, 23),
	(gen_random_uuid()::text, 'background', '/hero-bg/２５.JPG', NULL, 24),
	(gen_random_uuid()::text, 'background', '/hero-bg/２６.JPG', NULL, 25),
	(gen_random_uuid()::text, 'background', '/hero-bg/２７.JPG', NULL, 26),
	(gen_random_uuid()::text, 'background', '/hero-bg/２８.jpg', NULL, 27),
	(gen_random_uuid()::text, 'background', '/hero-bg/２９.JPG', NULL, 28),
	(gen_random_uuid()::text, 'background', '/hero-bg/３０.JPG', NULL, 29),
	(gen_random_uuid()::text, 'background', '/hero-bg/３１.JPG', NULL, 30),
	(gen_random_uuid()::text, 'background', '/hero-bg/３２.JPEG', NULL, 31),
	(gen_random_uuid()::text, 'background', '/hero-bg/３３.jpg', NULL, 32),
	(gen_random_uuid()::text, 'background', '/hero-bg/３４.JPG', NULL, 33),
	(gen_random_uuid()::text, 'background', '/hero-bg/３５.jpg', NULL, 34),
	(gen_random_uuid()::text, 'background', '/hero-bg/３６.jpg', NULL, 35),
	(gen_random_uuid()::text, 'background', '/hero-bg/３７.JPG', NULL, 36),
	(gen_random_uuid()::text, 'background', '/hero-bg/３８.jpg', NULL, 37),
	(gen_random_uuid()::text, 'background', '/hero-bg/３９.JPG', NULL, 38),
	(gen_random_uuid()::text, 'background', '/hero-bg/４０.JPEG', NULL, 39),
	(gen_random_uuid()::text, 'background', '/hero-bg/４１.JPG', NULL, 40),
	(gen_random_uuid()::text, 'background', '/hero-bg/４２.JPG', NULL, 41),
	(gen_random_uuid()::text, 'background', '/hero-bg/４３.jpg', NULL, 42),
	(gen_random_uuid()::text, 'background', '/hero-bg/４４.jpg', NULL, 43);
